config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :picks, only: [:index, :update, :create]
  get 'group_picks/index', to: 'group_picks#index'
  #post 'picks/create'
  #get 'picks/index'
  #get 'picks/update'
  #get 'picks/new'

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
	has_many :picks
	belongs_to :home_team, class_name: "Team", foreign_key: "ht_id"
	belongs_to :away_team, class_name: "Team", foreign_key: "at_id"

	def teams
		Team.where("id = ? OR id = ?", ht_id, at_id)
	end
end

app/models/pick.rb
class Pick < ApplicationRecord
	validate :user
	validate :game

	belongs_to :user
	belongs_to :game
	belongs_to :team
	
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :home_games, class_name: "Team", foreign_key: "ht_id"
	has_many :away_games, class_name: "Team", foreign_key: "at_id"

	def games
		Game.where("ht_id = ? OR at_id = ?", id, id)
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :picks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def current_user 
		if session[:user_id]
		  @current_user ||= User.find(session[:user_id])
		end
	end
end

app/controllers/group_picks_controller.rb
class GroupPicksController < ApplicationController
  def show
  	@group_picks = Pick.all(params[:pick_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]


  def create
    @pick = Pick.new(pick_params)
    @pick.user = current_user
    @pick.save
  end

  def update
    @pick = Pick.find(params[:id])
    @pick.update(pick_params)
  end

  def index
    @games = Game.where(week: "9", season: "2019")
    puts @games
    #if @games.empty
      #@games = TheRundown.get_games("9", "2019")
    #end
    @picks = current_user.picks.where(game_id: @games.pluck(:id))
    puts @games
    @new_picks = []
    @games.each do |game|
      unless @picks.detect {|pick| pick.game_id == game.id} 
        @new_picks.push(Pick.new(user: current_user, game: game))
      end
    end
    @new_picks.concat(@picks)
    @new_picks = @new_picks.sort_by(&:game_id)

  end

  def pick_params
    params.require(:pick).permit(:game_id, :team_id)
  end



end

 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_picks_helper.rb
module GroupPicksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/group_picks/index.html.erb
<br />
<div class="booyah-box col-10 offset-1 text-center">
	<h1>Group Picks</h1>
	<% User.all.each do |user| %>
  <%= user.id %>
  
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Punters and Pickers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', :media => 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <%= link_to 'Home Page', root_path, class: 'navbar-brand' %>
      <%= link_to 'My Picks', picks_path, class: 'navbar-brand' %>
      <%= link_to 'Group Picks', group_picks_index_path, class: 'navbar-brand' %>
      
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in?%>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>


    <%= yield %>
    <%= insert_paloma_hook %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="hero">
	<br />
	<div class="frosty col-10 offset-1 text-center">
		<br />
		<h1>Punters and Pickers</h1>
		<br />
		<h2>Make Your Picks</h2>
		<br />
		<%= link_to 'Picks', picks_path, class: 'btn btn-success' %>
		<br /><br />


	</div>
</div>

		

app/views/picks/create.html.erb
<br />
<div class="booyah-box col-10 offset-1 text-center">
	<h1>Punt or Pick</h1>
<br />

<%= link_to 'Punt My Picks', picks_create_path, class: 'btn btn-success' %>
<br />

	<div id='pickem-pick'>
	  <a>Team 1</a>
  	<input type="radio" name='team' id="box0" checked />
	</div>
<br />
	<div id='pickem-pick'>
		<a>Team 2</a>
		<input type="radio" name='team' id="box0" checked />
  </div>
  <br />
  
		<%= link_to 'Save Picks', picks_create_path, class: 'btn btn-success' %>
	<br />

	<% @new_picks.each do |pick| %>
		<% simple_form_for(pick) do |f| %>
			<%= f.input :team, as: :radio_buttons, collection: [pick.game.home_team, pick.game.away_team] %>
			<%= f.button :submit %>
		<% end %>
	<% end %>

</div>

app/views/picks/group_picks.html.erb
<br />
<div class="booyah-box col-10 offset-1 text-center">
	<h1>Group Picks</h1>
	<section class="col-a">
		<table class="type_entries">
			<thead>
				<tbody>
					<th class="rank"></th>
					<th class="entryowner">
						<span class="full">Entry, Owner</span>
					</th>
				</tbody>
			</thead>
		</table>
	</section>
	<button type="button" class="button autoPick button-alt">
		<div class="icon spinner_dashes loadingImg"></div>
		<span>::before"Punt My Picks"</span>

</div>

app/views/picks/index.html.erb
<br />
<div class="booyah-box col-10 offset-1 text-center">
	<h1>Punt or Pick</h1>
	<br />
		 <!-- <button class="btn btn-success" id="submitBtn">Punt My Picks</button> -->
	<br />
	<a1>Matchup</a1>
<br />

<% @new_picks.each do |pick| %>
  <%= simple_form_for(pick, remote: true, authenticity_token: true, html: { class: 'pick-form' } ) do |f| %>
 		<%= f.input :team_id, as: :radio_buttons, collection: [[pick.game.home_team.name, pick.game.ht_id], [pick.game.away_team.name, pick.game.at_id]] %>
 		<%= f.input :game_id, as: :hidden, input_html: { value:  pick.game_id } %> 
	<% end %>
<% end %>

  <button class="btn btn-success" id="submitBtn">Submit My Picks</button>
</form>

<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script>
	$(document).ready(function(){
  	$("#submitBtn").click(function(){        
      // $(".pick-form").submit(); // Submit the form
      $(".pick-form").each(
      	function(index, pickForm) {
      		// $(pickForm).serialize()
      		var form = $(pickForm)
      		$.ajax({
      			type: 'PUT',
      			url: form.attr("action"),
      			data: form.serialize(),
      			success: function() {}
      		})
      	}
      )
  	});
	});
</script>





        

                    

app/views/picks/picks.html.erb
<br />

<div class="booyah-box col-10 offset-1">
	<h1 class="text-center">Make Your Picks</h1>
	<hr />

	
	 </div>

app/views/picks/update.html.erb
<h1>Picks#update</h1>
<p>Find me in app/views/picks/update.html.erb</p>